# Modified from
# https://github.com/PyPSA/PyPSA/master/.travis.yml
language: python
sudo: false

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a

install:
  - conda create -q -n pyTrnsysType python=3.6
  - source activate pyTrnsysType
  - pip install --no-cache-dir .

script:
  - pytest --cov=pyTrnsysType --verbose tests/

after_success:
  - coverage report -m
  - coveralls